# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c03fa96e9098ecdb4966ea0d4144dbb392b5636707c5745a6509ccad221aa11e929daa23af84a77f7379a7c2e366738a6ed40c93ea5006975f3eab13a212ae2

test:
  secret_key_base: c76e11a5afd7d1d243b1168d2d2245c3be39dd84585c6648ef0e14f86e26c02e3d293f7d1b54982dac6c17c9cbfc66adc3225659ed155f943f2d255145fca88d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
